DELETE FROM Course;
INSERT INTO Course (cid, name) VALUES
("COS120", "Introduction to Computational Problem Solving"), 
("COS121", "Foundations of Computer Science"), 
("COS143", "Interactive Web Page Design"), 
("COS230", "Missions Technology"), 
("COS243", "Multi-tier Web Application Development"), 
("COS264", "IAD - Interactive Application Development"), 
("COS265", "Data Structures and Algorithms"), 
("COS280", "Introduction to Artificial Intelligence"), 
("COS284", "Introduction to Computer Systems"), 
("COS310", "Current Literature Survey"), 
("COS311", "Ethics in Computer Science"), 
("COS314", "Human Computer Interaction"), 
("COS320", "Algorithm Design"), 
("COS331 ", "Data Communications"), 
("COS340", "Software Engineering"), 
("COS341", "Database Concepts"), 
("COS343", "Advanced Database Concepts"), 
("COS350", "Graphics"), 
("COS351", "Computer Vision"), 
("COS371", "SWS I"), 
("COS372", "SWS II"), 
("COS380", "Natural Language Processing"), 
("COS381", "Computer Architecture"), 
("COS382", "Language Structures"), 
("COS393", "Practicum"), 
("COS421", "Operating Systems"), 
("COS424", "Surfaces and Modeling"), 
("COS425", "Animation"), 
("COS435", "Theory of Computation"), 
("COS426", "Distributed Processings"), 
("COS452", "Research I"), 
("COS453", "Research II"), 
("COS471", "SWS III"), 
("COS472", "SWS IIII"), 
("COS492", "Senior Project"), 
("COS493", "Capstone -- do we really have to answer questions about this?"), 
("MAT151", "Calculus"), 
("MAT215", "Discrete Math"), 
("MAT230", "Calculus II"), 
("MAT240", "Calculus III"), 
("MAT245", "Linear Algebra"), 
("MAT251", "Differential Equations"), 
("MAT310", "Mathematical Modeling with Numerical Analysis"), 
("MAT352", "Mathematical Statistics"), 
("SYS101", "Intro to Systems"), 
("SYS214", "Principles of Human Computer Interaction"), 
("SYS310", "E-Commerce"), 
("SYS352", "Knowledge Based Systems"), 
("SYS390", "Information Systems Analysis"), 
("SYS392", "Systems Seminar"), 
("SYS393", "Systems Practicum"), 
("SYS394", "Information Systems Design"), 
("SYS401", "Operations Research"), 
("SYS402", "Modeling and Simulation"), 
("SYS403", "Operations Management"), 
("SYS411", "Machine Learnin");